name: time_series
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - statsmodels=0.14.2
  - pmdarima=2.0.4
  - pip
  - pip:
      - prophet==1.1.5
      - holidays==0.43
      - plotly==5.22.0
      - optuna==3.6.1
      - ipykernel
      - pyarrow
      - fastparquet
      - openpyxl
      - xlrd
      - lxml
      - html5lib
      - beautifulsoup4

